"""Render a TriageResult as a prioritized, remediation-first Markdown report.

Designed to drop cleanly into a PR comment: a summary line a reviewer reads in
five seconds, a class breakdown (the thing you actually fix), then the ranked
findings with actionable findings first.
"""

from __future__ import annotations

from ..models import Severity, TriageResult

_SEV_EMOJI = {
    Severity.CRITICAL: "🔴",
    Severity.HIGH: "🟠",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🔵",
    Severity.INFO: "⚪",
}


def render_markdown(result: TriageResult) -> str:
    s = result.stats
    lines: list[str] = []
    lines.append("# 🛡️ Cullwise Triage Report")
    lines.append("")
    lines.append(
        f"**{s.raw_count}** raw findings → **{s.deduped_count}** unique → "
        f"**{s.actionable_count}** actionable "
        f"(**{s.false_positive_count}** likely false-positive / low-risk)."
    )
    lines.append("")

    # Vulnerability-class breakdown — fix by class, not by finding.
    if s.class_counts:
        lines.append("## Vulnerability classes")
        lines.append("")
        lines.append("| Class | Count |")
        lines.append("| --- | ---: |")
        for cls, count in s.class_counts.items():
            lines.append(f"| {cls} | {count} |")
        lines.append("")

    lines.append("## Findings (prioritized)")
    lines.append("")
    for t in result.findings:
        f = t.finding
        emoji = _SEV_EMOJI.get(t.adjusted_severity, "⚪")
        fp_tag = " · _likely false-positive_" if t.is_likely_false_positive else ""
        lines.append(
            f"### {emoji} {t.adjusted_severity.value} — {t.vulnerability_class}{fp_tag}"
        )
        lines.append("")
        lines.append(f"- **Location:** `{f.file_path}:{f.start_line}`")
        lines.append(f"- **Rule:** `{f.rule_id}`")
        if f.cwe:
            lines.append(f"- **CWE:** {', '.join(f.cwe)}")
        lines.append(
            f"- **Reported → adjusted:** {f.severity.value} → {t.adjusted_severity.value} "
            f"(confidence {t.confidence:.0%}, via {t.triaged_by})"
        )
        if t.exploitability:
            lines.append(f"- **Exploitability:** {t.exploitability}")
        lines.append(f"- **Remediation:** {t.remediation}")
        if t.rationale:
            lines.append(f"- **Why:** {t.rationale}")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by Cullwise · triage is advisory — confirm before acting._")
    return "\n".join(lines)
